Repository StructSure-LastProject/StructSure, pull requests merged in 2025-03, with the labels that each got.

#252 #247 fix bug button upload scan
  Android/app/src/main/java/fr/uge/structsure/structuresPage/domain/StructureViewModel.kt
Labels: 🤖 Android

#259 #245-Recherche-des-ouvrages
  Frontend/src/components/AdminPanel/AddAccountModal.jsx
  Frontend/src/components/AdminPanel/EditAccountModal.jsx
Labels: 🌐 Web

#260 #241 fix bug sensors color on alert modal
  Android/app/src/main/java/fr/uge/structsure/components/Plan.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/AlertPage.kt
Labels: 🤖 Android

#262 #248 fix bug modal ble connection
  Android/app/src/main/java/fr/uge/structsure/bluetooth/cs108/Cs108Connector.kt
  Android/app/src/main/java/fr/uge/structsure/bluetooth/cs108/TimedDevicesList.kt
  Android/app/src/main/java/fr/uge/structsure/bluetooth/presentation/BluetoothPage.kt
  Backend/src/main/java/fr/uge/structsure/config/JwtFilter.java
  Backend/src/main/java/fr/uge/structsure/config/SpringSecurityConfig.java
  Backend/src/main/java/fr/uge/structsure/utils/GlobalExceptionHandler.java
  Backend/src/test/resources/application.properties
Labels: 🤖 Android

#265 #243-Boutons-de-zoom-sur-un-plan
  Backend/.gitignore
  Backend/src/main/resources/application.properties
  Frontend/src/components/StructureDetail/StructureDetailCanvas.jsx
Labels: 🌐 Web

#258 #250-ouvrage-sans-resultats-affiches-OK
  Backend/src/main/java/fr/uge/structsure/repositories/StructureRepositoryCriteriaQuery.java
Labels: 🌐 Web

#282 #273 Champ date du volet capteur
  Backend/src/main/java/fr/uge/structsure/dto/sensors/EditSensorRequestDTO.java
  Backend/src/main/java/fr/uge/structsure/services/SensorService.java
  Frontend/src/components/SensorPanel/SensorFieldComponent.jsx
  Frontend/src/components/SensorPanel/SensorPanel.jsx
Labels: 🌐 Web

#285 FIX BUG MODAL ADDING sensors with correct format (id HEXA)
  Frontend/src/components/Sensor/ModalAddSensor.jsx
Labels: 🌐 Web

#286 #102 interface de filtre et tri des ouvragres
  Backend/src/main/java/fr/uge/structsure/dto/structure/AllStructureRequestDTO.java
  Backend/src/main/java/fr/uge/structsure/repositories/StructureRepositoryCriteriaQuery.java
  Backend/src/main/java/fr/uge/structsure/services/StructureService.java
  Frontend/src/components/LstStructureHead.jsx
  Frontend/src/components/StructSureBody.jsx
  Frontend/src/components/Structure.jsx
  Frontend/src/components/StructuresFilter.jsx
Labels: 🌐 Web

#261 #244 Autorisation des espaces dans les noms de capteur
  Backend/src/main/java/fr/uge/structsure/services/SensorService.java
  Frontend/src/components/Sensor/ModalAddSensor.jsx
  Frontend/src/components/SensorPanel/SensorPanel.jsx
Labels: 🌐 Web

#264 #45-Personnaliser-un-mot-de-passe-utilisateur
  Backend/src/main/java/fr/uge/structsure/controllers/AuthenticationController.java
  Backend/src/main/java/fr/uge/structsure/dto/auth/ChangePasswordRequestDTO.java
  Backend/src/main/java/fr/uge/structsure/dto/auth/ChangePasswordResponseDTO.java
  Backend/src/main/java/fr/uge/structsure/dto/auth/LoginResponseDTO.java
  Backend/src/main/java/fr/uge/structsure/entities/Account.java
  Backend/src/main/java/fr/uge/structsure/exceptions/Error.java
  Backend/src/main/java/fr/uge/structsure/repositories/AccountRepository.java
  Backend/src/main/java/fr/uge/structsure/services/AccountService.java
  Frontend/src/components/AccountChangePassword.jsx
  Frontend/src/components/Login.jsx
  Frontend/src/pages/Account.jsx
Labels: 🌐 Web

#284 #269-popup-de-placement-de-capteur
  Frontend/src/components/Sensor/ModalAddSensor.jsx
  Frontend/src/components/StructureDetail/StructureDetailBody.jsx
  Frontend/src/components/StructureDetail/StructureDetailCanvas.jsx
  Frontend/src/components/StructureDetail/StructureDetailCapteurs.jsx
  Frontend/src/components/StructureDetail/StructureDetailRow.jsx
Labels: 🌐 Web

#291 #289 - Confirmation de suppresion d'un ouvage
  Android/app/src/main/java/fr/uge/structsure/components/Buttons.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/presentation/components/ConfirmPopup.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/presentation/components/StructureButtons.kt
Labels: 🤖 Android

#293 #274 Pagination
  Backend/src/main/java/fr/uge/structsure/repositories/SensorRepositoryCriteriaQuery.java
  Frontend/src/components/Pagination.jsx
  Frontend/src/components/StructureDetail/StructureDetailBody.jsx
  Frontend/src/components/StructureDetail/StructureDetailCapteurs.jsx
Labels: 🌐 Web

#287 #239 JWToken renewal
  Backend/src/main/java/fr/uge/structsure/config/JwtFilter.java
  Backend/src/main/java/fr/uge/structsure/config/JwtUtils.java
  Frontend/src/components/Header.jsx
  Frontend/src/components/Login.jsx
  Frontend/src/hooks/useFetch.js
Labels: 🌐 Web

#298 #288 Confirmation pour anonymiser
  Frontend/src/components/AdminPanel/ConfirmationDeleteModal.jsx
  Frontend/src/components/AdminPanel/EditAccountModal.jsx
Labels: 🌐 Web

#283 #275 Plusieurs plans même fichier
  Backend/src/main/java/fr/uge/structsure/repositories/PlanRepository.java
  Backend/src/main/java/fr/uge/structsure/services/PlanService.java
Labels: 🌐 Web

#300 #NA Pagination bug fix
  Frontend/src/components/Pagination.jsx
Labels: 🌐 Web

#299 #268-Plan-mis-a-jour-dans-le-canvas
  Frontend/src/components/Plan/DropdownsSection.jsx
  Frontend/src/components/Plan/ModalEditPlan.jsx
  Frontend/src/components/StructureDetail/StructureDetailPlans.jsx
  Frontend/src/components/StructureDetail/StructureDetailSection.jsx
Labels: 🌐 Web

#301 #25-Exporter-les-Résultats-d’un-scan-au-format-CSV
  Backend/src/main/java/fr/uge/structsure/dto/sensors/AllSensorsByStructureRequestDTO.java
  Backend/src/main/java/fr/uge/structsure/repositories/SensorRepositoryCriteriaQuery.java
  Backend/src/main/java/fr/uge/structsure/services/StructureService.java
  Backend/src/test/java/fr/uge/structsure/DataBaseTests.java
  Backend/src/test/java/fr/uge/structsure/StructsureBackendApplicationTests.java
  Backend/src/test/java/fr/uge/structsure/services/AccountServiceTest.java
  Backend/src/test/java/fr/uge/structsure/services/PlanServiceTest.java
  Backend/src/test/java/fr/uge/structsure/services/SensorServiceTest.java
  Frontend/package.json
  Frontend/src/components/Alert.jsx
  Frontend/src/components/StructureDetail/StructureDetailBody.jsx
  Frontend/src/components/StructureDetail/StructureDetailCapteurs.jsx
  Frontend/src/components/StructureDetail/StructureDetailHead.jsx
Labels: 🌐 Web

#294 #272-Settings-in-URL
  Frontend/src/components/Pagination.jsx
  Frontend/src/components/Plan/DropdownsSection.jsx
  Frontend/src/components/SensorFilter.jsx
  Frontend/src/components/SensorPanel/SensorFieldComponent.jsx
  Frontend/src/components/StructureDetail/StructureDetailBody.jsx
  Frontend/src/components/StructureDetail/StructureDetailCapteurs.jsx
  Frontend/src/components/StructureDetail/StructureDetailHead.jsx
  Frontend/src/components/StructureDetail/StructureDetailPlans.jsx
Labels: 🌐 Web

#303 #302 Fix jwt breach and duplication
  Backend/src/main/java/fr/uge/structsure/config/JwtFilter.java
  Frontend/src/components/AccountChangePassword.jsx
  Frontend/src/components/AdminPanel/AddAccountModal.jsx
  Frontend/src/components/AdminPanel/ConfirmationDeleteModal.jsx
  Frontend/src/components/AdminPanel/EditAccountModal.jsx
  Frontend/src/components/AdminPanelBody.jsx
  Frontend/src/components/ArchiveModal.jsx
  Frontend/src/components/LstStructureHead.jsx
  Frontend/src/components/RestoreModal.jsx
  Frontend/src/components/Sensor/ModalAddSensor.jsx
  Frontend/src/components/SensorPanel/SensorPanel.jsx
  Frontend/src/components/StructSureBody.jsx
  Frontend/src/components/StructureDetail/StructureDetailBody.jsx
  Frontend/src/components/StructureDetail/StructureDetailCanvas.jsx
  Frontend/src/components/StructureDetail/StructureDetailCapteurs.jsx
  Frontend/src/components/StructureDetail/StructureDetailEdit.jsx
  Frontend/src/hooks/useFetch.js
Labels: 🌐 Web

#308 #NA Pagination edit sensor bug & Archive filter access
  Frontend/src/components/AccountChangePassword.jsx
  Frontend/src/components/AdminPanel/AddAccountModal.jsx
  Frontend/src/components/AdminPanel/EditAccountModal.jsx
  Frontend/src/components/SensorFilter.jsx
  Frontend/src/components/SensorPanel/SensorPanel.jsx
  Frontend/src/components/StructureDetail/StructureDetailCapteurs.jsx
Labels: 🌐 Web

#309 #-Bug-Fix-Edit-Image-Show-Existing-Image
  Frontend/src/components/Modal/ModalImage.jsx
Labels: 🌐 Web

#306 #305 non protected endpoints
  Backend/src/main/java/fr/uge/structsure/config/RequiresRole.java
  Backend/src/main/java/fr/uge/structsure/config/RoleFilter.java
  Backend/src/main/java/fr/uge/structsure/config/SpringSecurityConfig.java
  Backend/src/main/java/fr/uge/structsure/controllers/AndroidScanController.java
  Backend/src/main/java/fr/uge/structsure/controllers/AuthenticationController.java
  Backend/src/main/java/fr/uge/structsure/controllers/SensorController.java
  Backend/src/main/java/fr/uge/structsure/controllers/StructureController.java
  Backend/src/main/java/fr/uge/structsure/controllers/UserAccountController.java
  Backend/src/main/java/fr/uge/structsure/entities/Account.java
  Backend/src/main/java/fr/uge/structsure/services/AccountService.java
  Backend/src/main/java/fr/uge/structsure/services/PlanService.java
  Backend/src/main/java/fr/uge/structsure/services/SensorService.java
  Backend/src/main/java/fr/uge/structsure/services/StructureService.java
Labels: 🌐 Web

#310 Plans section toggle fix
  Backend/src/main/java/fr/uge/structsure/services/PlanService.java
  Frontend/src/components/Plan/DropdownsSection.jsx
Labels: 🌐 Web

#311 Sort StructuresListView
  Android/app/src/main/AndroidManifest.xml
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/AlertPage.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/presentation/components/Structure.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/presentation/components/StructureButtons.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/presentation/components/StructuresListView.kt
Labels: 🤖 Android

#323 #321 details capteurs
  Android/app/src/main/java/fr/uge/structsure/components/Containers.kt
  Android/app/src/main/java/fr/uge/structsure/components/Plan.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/domain/ChipFinder.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/ScanPage.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/components/ScanWeather.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/components/SensorsList.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/presentation/components/ConfirmPopup.kt
Labels: 🤖 Android

#325 #NA fix UI
  Frontend/src/components/Login.jsx
  Frontend/src/components/Pagination.jsx
  Frontend/src/pages/Account.jsx
Labels: 🌐 Web

#312 #NA-fix-plan-image-deleted-in-front
  Frontend/src/assets/image_plan_not_found.png
  Frontend/src/components/AccountChangePassword.jsx
  Frontend/src/components/Modal/ModalComment.jsx
  Frontend/src/components/Modal/ModalImage.jsx
  Frontend/src/components/Plan/DropdownsSection.jsx
  Frontend/src/components/Plan/ModalAddPlan.jsx
  Frontend/src/components/Plan/ModalEditPlan.jsx
  Frontend/src/components/StructureDetail/StructureDetailBody.jsx
  Frontend/src/components/StructureDetail/StructureDetailCanvas.jsx
  Frontend/src/components/StructureDetail/StructureDetailEdit.jsx
  Frontend/src/components/StructureDetail/StructureDetailHead.jsx
  Frontend/src/components/StructureDetail/StructureDetailPlans.jsx
Labels: 🌐 Web

#328 #319 clic sur un capteur
  Frontend/src/components/SensorPanel/SensorPanel.jsx
  Frontend/src/components/StructureDetail/StructureDetailCanvas.jsx
  Frontend/src/components/StructureDetail/StructureDetailCanvasModals.jsx
  Frontend/src/components/StructureDetail/StructureDetailCapteurs.jsx
Labels: 🌐 Web

#317 #316-Controles-nouvel-ouvrage
  Backend/src/main/java/fr/uge/structsure/exceptions/Error.java
  Backend/src/main/java/fr/uge/structsure/services/StructureService.java
  Frontend/src/components/LstStructureHead.jsx
  Frontend/src/components/StructSureBody.jsx
Labels: 🌐 Web

#330 #320 date installation ajout de capteur
  Backend/src/main/java/fr/uge/structsure/dto/sensors/BaseSensorDTO.java
  Backend/src/main/java/fr/uge/structsure/entities/Sensor.java
  Backend/src/main/java/fr/uge/structsure/services/ScanService.java
  Backend/src/main/java/fr/uge/structsure/services/SensorService.java
  Backend/src/test/java/fr/uge/structsure/services/SensorServiceTest.java
  Frontend/src/components/Sensor/ModalAddSensor.jsx
Labels: 🌐 Web

#324 #NA Droits ouvrages optimisation Backend
  Backend/src/main/java/fr/uge/structsure/controllers/UserAccountController.java
  Backend/src/main/java/fr/uge/structsure/dto/userAccount/accountStructure/UpdateUserStructureAccessResponseDTO.java
  Backend/src/main/java/fr/uge/structsure/services/AccountService.java
  Backend/src/main/java/fr/uge/structsure/services/AccountStructureService.java
  Backend/src/main/java/fr/uge/structsure/services/AppLogService.java
  Backend/src/main/java/fr/uge/structsure/services/PlanService.java
  Backend/src/main/java/fr/uge/structsure/services/StructureService.java
Labels: 🌐 Web

#331 #322-BUG-capteurs-plans
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/SensorValidator.kt
  Backend/src/main/java/fr/uge/structsure/entities/SensorId.java
  Frontend/src/components/Sensor/ModalAddSensor.jsx
  Frontend/src/components/SensorPanel/SensorPanel.jsx
Labels: 🤖 Android, 🌐 Web

#326 #313 Remove sensor from plan
  Android/app/src/main/java/fr/uge/structsure/components/Plan.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/repository/ScanRepository.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/domain/PlanViewModel.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/PlansView.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/ScanPage.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/SensorDao.kt
  Backend/src/main/java/fr/uge/structsure/dto/plan/PlanMetadataDTO.java
  Backend/src/main/java/fr/uge/structsure/dto/scan/AndroidSensorEditDTO.java
  Backend/src/main/java/fr/uge/structsure/dto/userAccount/UserUpdateRequestDTO.java
  Backend/src/main/java/fr/uge/structsure/services/ScanService.java
  Backend/src/main/java/fr/uge/structsure/utils/DiffMaker.java
  Backend/src/main/java/fr/uge/structsure/utils/GlobalExceptionHandler.java
Labels: 🤖 Android
