Repository StructSure-LastProject/StructSure, pull requests merged in 2025-02, with the labels that each got.

#116 #na spring security upgrade
  Backend/src/main/java/fr/uge/structsure/StructSureBackendApplication.java
  Backend/src/main/java/fr/uge/structsure/config/JwtFilter.java
  Backend/src/main/java/fr/uge/structsure/config/SpringSecurityConfig.java
  Backend/src/main/java/fr/uge/structsure/controllers/FrontController.java
  Backend/src/main/resources/application.properties
Labels: MergeRequest

#87 #na clean start scan
  Android/app/src/main/java/fr/uge/structsure/MainActivity.kt
  Android/app/src/main/java/fr/uge/structsure/alertes/Alertes.kt
  Android/app/src/main/java/fr/uge/structsure/bluetooth/presentation/BluetoothPage.kt
  Android/app/src/main/java/fr/uge/structsure/components/BluetoothButton.kt
  Android/app/src/main/java/fr/uge/structsure/components/Page.kt
  Android/app/src/main/java/fr/uge/structsure/startScan/presentation/MainScreenStartSensor.kt
  Android/app/src/main/java/fr/uge/structsure/startScan/presentation/PlansView.kt
  Android/app/src/main/java/fr/uge/structsure/startScan/presentation/ToolBar.kt
  Android/app/src/main/java/fr/uge/structsure/startScan/presentation/components/SensorState.kt
  Android/app/src/main/java/fr/uge/structsure/startScan/presentation/components/SensorsList.kt
  Android/app/src/main/java/fr/uge/structsure/startScan/presentation/components/SharedComponents.kt
  Android/app/src/main/java/fr/uge/structsure/startScan/presentation/components/StructureWeather.kt
  Android/app/src/main/java/fr/uge/structsure/startScan/presentation/sensors/list/SensorItem.kt
  Android/app/src/main/java/fr/uge/structsure/startScan/presentation/sensors/list/SensorList.kt
  Android/app/src/main/java/fr/uge/structsure/startScan/presentation/sensors/list/SensorsListView.kt
  Android/app/src/main/java/fr/uge/structsure/startScan/presentation/sensors/status/ScanSummaryView.kt
  Android/app/src/main/java/fr/uge/structsure/startScan/presentation/sensors/status/SensorStatus.kt
  Android/app/src/main/java/fr/uge/structsure/startScan/presentation/sensors/status/SensorStatusCircle.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/presentation/HomePage.kt
Labels: MergeRequest

#122 Add sensor endpoint done
  Backend/src/main/java/fr/uge/structsure/controllers/SensorController.java
  Backend/src/main/java/fr/uge/structsure/dto/sensors/AddSensorAnswerDTO.java
  Backend/src/main/java/fr/uge/structsure/dto/sensors/AddSensorRequestDTO.java
  Backend/src/main/java/fr/uge/structsure/exceptions/ErrorIdentifier.java
  Backend/src/main/java/fr/uge/structsure/exceptions/ErrorMessages.java
  Backend/src/main/java/fr/uge/structsure/repositories/SensorRepository.java
  Backend/src/main/java/fr/uge/structsure/services/SensorService.java
Labels: MergeRequest

#127 #115 liste des comptes dynamique
  Backend/src/main/java/fr/uge/structsure/config/CorsConfig.java
  Backend/src/main/java/fr/uge/structsure/controllers/UserAccountController.java
  Backend/src/main/java/fr/uge/structsure/dto/userAccount/UserAccountResponseDTO.java
  Backend/src/main/java/fr/uge/structsure/entities/Role.java
  Backend/src/main/java/fr/uge/structsure/services/AccountService.java
  Frontend/src/components/AccountDetails.jsx
  Frontend/src/components/AdminPanelBody.jsx
  Frontend/src/index.css
Labels: MergeRequest

#133 #119 modale ajout de compte
  Frontend/src/components/AccountDetails.jsx
  Frontend/src/components/AdminPanel/EditAccountModal.jsx
  Frontend/src/components/AdminPanelBody.jsx
  Frontend/src/components/AdminPanelBottom.jsx
  Frontend/src/components/StructureNameCard.jsx
  Frontend/src/pages/AdminPanel.jsx
Labels: MergeRequest

#138 add dev env
  .github/workflows/Build.yaml
Labels: MergeRequest

#125 #79 sauvegarde des interrogation en local
  Android/app/src/androidTest/java/fr/uge/structsure/scanPage/domain/TimedBufferTests.kt
  Android/app/src/main/java/fr/uge/structsure/MainActivity.kt
  Android/app/src/main/java/fr/uge/structsure/alertes/Alertes.kt
  Android/app/src/main/java/fr/uge/structsure/bluetooth/cs108/Cs108Connector.kt
  Android/app/src/main/java/fr/uge/structsure/bluetooth/cs108/Cs108Scanner.kt
  Android/app/src/main/java/fr/uge/structsure/components/CustomToast.kt
  Android/app/src/main/java/fr/uge/structsure/components/Plan.kt
  Android/app/src/main/java/fr/uge/structsure/connexionPage/data/AccountDao.kt
  Android/app/src/main/java/fr/uge/structsure/database/AppDatabase.kt
  Android/app/src/main/java/fr/uge/structsure/retrofit/RetrofitInstance.kt
  Android/app/src/main/java/fr/uge/structsure/retrofit/response/GetAllStructureResponse.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/ResultSensors.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/ScanEntity.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/StructureEntity.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/cache/SensorCache.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/dao/ResultDao.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/dao/ScanDao.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/dao/StructurePlanDao.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/domain/AlertInfo.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/domain/ScanState.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/domain/ScanViewModel.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/domain/TimedBuffer.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/DisplayPlanImages.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/PlansView.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/ScanPage.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/ToolBar.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/components/SensorState.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/components/SensorsList.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/components/SharedComponents.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/components/StructureWeather.kt
  Android/app/src/main/java/fr/uge/structsure/startScan/data/ResultEntity.kt
  Android/app/src/main/java/fr/uge/structsure/startScan/data/dao/ScanDao.kt
  Android/app/src/main/java/fr/uge/structsure/startScan/domain/ScanViewModel.kt
  Android/app/src/main/java/fr/uge/structsure/startScan/domain/StructureViewModel.kt
  Android/app/src/main/java/fr/uge/structsure/startScan/presentation/MainScreenStartSensor.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/PlanDao.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/Sensor.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/SensorDao.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/StructureData.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/StructureDetailsData.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/StructureRepository.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/presentation/components/StructureButtons.kt
  Backend/src/main/java/fr/uge/structsure/controllers/StructureController.java
  Backend/src/main/java/fr/uge/structsure/dto/sensors/SensorFilterDTO.java
  Backend/src/main/java/fr/uge/structsure/entities/Sensor.java
  Backend/src/main/java/fr/uge/structsure/entities/SensorId.java
  Backend/src/main/java/fr/uge/structsure/services/SensorService.java
Labels: MergeRequest

#139 #98 Add new settings Page
  Android/app/build.gradle.kts
  Android/app/src/main/java/fr/uge/structsure/MainActivity.kt
  Android/app/src/main/java/fr/uge/structsure/alertes/Alertes.kt
  Android/app/src/main/java/fr/uge/structsure/components/Header.kt
  Android/app/src/main/java/fr/uge/structsure/components/Page.kt
  Android/app/src/main/java/fr/uge/structsure/connexionPage/Connexion.kt
  Android/app/src/main/java/fr/uge/structsure/database/AppDatabase.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/dao/ResultDao.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/ScanPage.kt
  Android/app/src/main/java/fr/uge/structsure/settings/domain/SettingsLogics.kt
  Android/app/src/main/java/fr/uge/structsure/settings/domain/States.kt
  Android/app/src/main/java/fr/uge/structsure/settings/presentation/SettingsPage.kt
  Android/app/src/main/java/fr/uge/structsure/settingsPage/presentation/SettingsPage.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/presentation/HomePage.kt
  Android/gradle/libs.versions.toml
Labels: MergeRequest

#142 #113 ajout d'un plan sur le serveur
  Backend/src/main/java/fr/uge/structsure/controllers/StructureController.java
  Backend/src/main/java/fr/uge/structsure/dto/plan/AddPlanRequestDTO.java
  Backend/src/main/java/fr/uge/structsure/entities/Plan.java
  Backend/src/main/java/fr/uge/structsure/exceptions/ErrorIdentifier.java
  Backend/src/main/java/fr/uge/structsure/exceptions/ErrorMessages.java
  Backend/src/main/java/fr/uge/structsure/repositories/PlanRepository.java
  Backend/src/main/java/fr/uge/structsure/services/PlanService.java
  Backend/src/main/resources/application.properties
  Frontend/src/components/Plan/ModalAddPlan.jsx
  Frontend/src/components/StructureDetailPlans.jsx
  Frontend/src/hooks/useFetch.js
Labels: New Feature

#144 #6 connaître la liste des scans sur un ouvrage
  Backend/src/main/java/fr/uge/structsure/dto/structure/StructureDetailsResponseDTO.java
  Backend/src/main/java/fr/uge/structsure/entities/Scan.java
  Backend/src/main/java/fr/uge/structsure/repositories/ScanRepository.java
  Backend/src/main/java/fr/uge/structsure/services/StructureService.java
  Frontend/src/App.jsx
  Frontend/src/components/Header.jsx
  Frontend/src/components/StructSureBody.jsx
  Frontend/src/components/StructureDetailBody.jsx
  Frontend/src/components/StructureDetailHead.jsx
  Frontend/src/pages/StructureDetail.jsx
Labels: MergeRequest

#149 #na fix unauthorized error
  Backend/src/main/java/fr/uge/structsure/controllers/FrontController.java
  Frontend/index.html
  Frontend/public/favicon.ico
  Frontend/public/vite.svg
Labels: MergeRequest

#151 Hotfix section field (plan) not added to bdd
  Backend/src/main/java/fr/uge/structsure/entities/Plan.java
  Backend/src/main/java/fr/uge/structsure/services/PlanService.java
Labels: Hotfix

#152 #121-Sauvegarde de l'ajout de compte côté serveur
  Backend/src/main/java/fr/uge/structsure/controllers/UserAccountController.java
  Backend/src/main/java/fr/uge/structsure/entities/Role.java
  Backend/src/main/java/fr/uge/structsure/exceptions/ErrorIdentifier.java
  Backend/src/main/java/fr/uge/structsure/exceptions/ErrorMessages.java
  Backend/src/main/java/fr/uge/structsure/services/AccountService.java
  Backend/src/main/java/fr/uge/structsure/utils/userAccountRequestValidation/UserAccountRequestValidation.java
  Frontend/src/components/AdminPanel/AddAccountModal.jsx
  Frontend/src/components/AdminPanel/EditAccountModal.jsx
  Frontend/src/components/AdminPanelBody.jsx
  Frontend/src/hooks/useFetch.js
  Frontend/src/hooks/vaildateUserAccountForm.js
Labels: MergeRequest

#154 #93 gestion du ble non initialise
  Android/app/src/main/java/fr/uge/structsure/bluetooth/cs108/Cs108Connector.kt
  Android/app/src/main/java/fr/uge/structsure/bluetooth/cs108/Cs108Scanner.kt
  Android/app/src/main/java/fr/uge/structsure/bluetooth/cs108/RfidChip.kt
  Android/app/src/main/java/fr/uge/structsure/components/BluetoothButton.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/domain/ScanViewModel.kt
Labels: Bug

#180 add Test CI
  .github/workflows/Test.yaml
  .gitignore
  Frontend/package.json
  Frontend/src/test/Home.test.jsx
Labels: MergeRequest

#143 #99 reglage de lurl du serveur
  Android/app/src/main/java/fr/uge/structsure/MainActivity.kt
  Android/app/src/main/java/fr/uge/structsure/connexionPage/Authentication.kt
  Android/app/src/main/java/fr/uge/structsure/retrofit/RetrofitInstance.kt
  Android/app/src/main/java/fr/uge/structsure/settingsPage/presentation/PreferencesManager.kt
  Android/app/src/main/java/fr/uge/structsure/settingsPage/presentation/SettingsPage.kt
Labels: MergeRequest

#176 #41 add update role
  Backend/src/main/java/fr/uge/structsure/controllers/UserAccountController.java
  Backend/src/main/java/fr/uge/structsure/dto/userAccount/RoleRequest.java
  Backend/src/main/java/fr/uge/structsure/exceptions/ErrorIdentifier.java
  Backend/src/main/java/fr/uge/structsure/exceptions/ErrorMessages.java
  Backend/src/main/java/fr/uge/structsure/services/AccountService.java
  Frontend/src/components/AccountDetails.jsx
  Frontend/src/components/AdminPanel/AddAccountModal.jsx
  Frontend/src/components/AdminPanel/EditAccountModal.jsx
  Frontend/src/components/AdminPanelBody.jsx
Labels: MergeRequest

#181 Factorizing error messages in one single enum
  Backend/src/main/java/fr/uge/structsure/controllers/AuthenticationController.java
  Backend/src/main/java/fr/uge/structsure/controllers/SensorController.java
  Backend/src/main/java/fr/uge/structsure/controllers/StructureController.java
  Backend/src/main/java/fr/uge/structsure/controllers/UserAccountController.java
  Backend/src/main/java/fr/uge/structsure/exceptions/Error.java
  Backend/src/main/java/fr/uge/structsure/exceptions/ErrorIdentifier.java
  Backend/src/main/java/fr/uge/structsure/exceptions/ErrorMessages.java
  Backend/src/main/java/fr/uge/structsure/exceptions/TraitementException.java
  Backend/src/main/java/fr/uge/structsure/services/AccountService.java
  Backend/src/main/java/fr/uge/structsure/services/PlanService.java
  Backend/src/main/java/fr/uge/structsure/services/SensorService.java
  Backend/src/main/java/fr/uge/structsure/services/StructureService.java
  Backend/src/test/java/fr/uge/structsure/services/AccountServiceTest.java
  Backend/src/test/java/fr/uge/structsure/services/PlanServiceTest.java
  Backend/src/test/java/fr/uge/structsure/services/SensorServiceTest.java
Labels: MergeRequest

#187 #162 Ajout du super admin par défaut
  Backend/src/main/java/fr/uge/structsure/StructSureBackendApplication.java
  Backend/src/main/java/fr/uge/structsure/controllers/FrontController.java
  Backend/src/main/java/fr/uge/structsure/services/AccountService.java
  Backend/src/test/java/fr/uge/structsure/services/AccountServiceTest.java
Labels: MergeRequest

#190 #189 - Bug resolved
  .gitignore
  Backend/src/main/java/fr/uge/structsure/entities/Plan.java
  Backend/src/main/java/fr/uge/structsure/entities/Sensor.java
  Backend/src/main/java/fr/uge/structsure/entities/Structure.java
Labels: Bug

#179 #92 telechargement des plans
  Android/app/src/main/java/fr/uge/structsure/MainActivity.kt
  Android/app/src/main/java/fr/uge/structsure/components/Plan.kt
  Android/app/src/main/java/fr/uge/structsure/database/AppDatabase.kt
  Android/app/src/main/java/fr/uge/structsure/retrofit/StructureApi.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/dao/StructurePlanDao.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/domain/PlanViewModel.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/PlansView.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/ScanPage.kt
  Android/app/src/main/java/fr/uge/structsure/settingsPage/presentation/PreferencesManager.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/PlanDao.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/SensorDao.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/StructureRepository.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/domain/StructureViewModel.kt
  Android/app/src/main/java/fr/uge/structsure/utils/FileUtils.kt
  Android/gradle/libs.versions.toml
  Backend/src/main/java/fr/uge/structsure/controllers/StructureController.java
  Backend/src/main/java/fr/uge/structsure/services/PlanService.java
  Backend/src/main/resources/application.properties
Labels: MergeRequest

#191 #174 Restrictions d'acces
  Backend/src/main/java/fr/uge/structsure/controllers/UserAccountController.java
  Backend/src/main/java/fr/uge/structsure/dto/userAccount/UserStructureAccessRequestDTO.java
  Backend/src/main/java/fr/uge/structsure/dto/userAccount/accountStructure/StructurePermission.java
  Backend/src/main/java/fr/uge/structsure/dto/userAccount/accountStructure/UpdateUserStructureAccessResponseDTO.java
  Backend/src/main/java/fr/uge/structsure/entities/Account.java
  Backend/src/main/java/fr/uge/structsure/entities/Structure.java
  Backend/src/main/java/fr/uge/structsure/exceptions/Error.java
  Backend/src/main/java/fr/uge/structsure/repositories/AccountRepository.java
  Backend/src/main/java/fr/uge/structsure/services/AccountService.java
  Backend/src/main/java/fr/uge/structsure/services/AccountStructureService.java
Labels: MergeRequest

#192 #170 volet de capteur statique & #171 Volet de capteur dynamique(pas plan)
  Frontend/src/components/SensorPanel/SensorFieldComponent.jsx
  Frontend/src/components/SensorPanel/SensorPanel.jsx
  Frontend/src/components/SensorStatusColorGen.jsx
  Frontend/src/components/StructureDetail/StructureDetailCapteurs.jsx
  Frontend/src/index.css
Labels: MergeRequest

#195 #145 selecteur de plan dynamique
  Backend/src/main/java/fr/uge/structsure/dto/structure/StructureDetailsResponseDTO.java
  Backend/src/main/java/fr/uge/structsure/entities/Result.java
  Backend/src/main/java/fr/uge/structsure/entities/Scan.java
  Backend/src/main/java/fr/uge/structsure/entities/Sensor.java
  Frontend/src/components/Plan/DropdownsSection.jsx
  Frontend/src/components/Plan/ModalAddPlan.jsx
  Frontend/src/components/Plan/ModalEditPlan.jsx
  Frontend/src/components/StructureDetail/StructureDetailBody.jsx
  Frontend/src/components/StructureDetail/StructureDetailPlans.jsx
  Frontend/src/components/StructureDetail/StructureDetailSection.jsx
Labels: MergeRequest

#188 #165 pagination des capteurs d'un ouvrage
  Backend/src/main/java/fr/uge/structsure/controllers/SensorController.java
  Backend/src/main/java/fr/uge/structsure/dto/sensors/AllSensorsByStructureRequestDTO.java
  Backend/src/main/java/fr/uge/structsure/dto/sensors/SensorDTO.java
  Backend/src/main/java/fr/uge/structsure/entities/Plan.java
  Backend/src/main/java/fr/uge/structsure/entities/Scan.java
  Backend/src/main/java/fr/uge/structsure/entities/Sensor.java
  Backend/src/main/java/fr/uge/structsure/entities/Structure.java
  Backend/src/main/java/fr/uge/structsure/exceptions/Error.java
  Backend/src/main/java/fr/uge/structsure/repositories/SensorRepositoryCriteriaQuery.java
  Backend/src/main/java/fr/uge/structsure/services/SensorService.java
  Backend/src/main/java/fr/uge/structsure/utils/EnumValidatorFromString.java
  Backend/src/test/java/fr/uge/structsure/services/SensorServiceTest.java
  Frontend/src/components/StructureDetail/StructureDetailBody.jsx
Labels: MergeRequest

#196 #155 selecteur de plan dynamique
  Android/.idea/icon.svg
  Android/app/src/main/java/fr/uge/structsure/MainActivity.kt
  Android/app/src/main/java/fr/uge/structsure/components/Plan.kt
  Android/app/src/main/java/fr/uge/structsure/connexionPage/Authentication.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/PlanTree.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/repository/ScanRepository.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/domain/PlanViewModel.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/domain/ScanViewModel.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/PlansView.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/ScanPage.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/components/ScanWeather.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/PlanDao.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/Sensor.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/SensorDao.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/StructureRepository.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/domain/StructureViewModel.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/presentation/ConnectivityStatus.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/presentation/components/Structure.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/presentation/components/StructureButtons.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/presentation/components/StructuresListView.kt
  Android/app/src/main/res/drawable/oa_plan.png
  Android/app/src/main/res/drawable/plan_not_found.png
  Android/app/src/main/res/drawable/plan_p1.jpeg
  Android/app/src/main/res/drawable/plan_p2.jpeg
  Android/app/src/main/res/drawable/plan_p3.png
  Android/app/src/main/res/drawable/plan_p4.jpeg
  Android/app/src/main/res/drawable/plan_p5.png
  Android/app/src/main/res/drawable/plan_p6.jpeg
  Android/app/src/main/res/drawable/plan_p7.jpeg
  Android/app/src/main/res/drawable/plan_p8.jpg
  Backend/src/main/java/fr/uge/structsure/dto/structure/StructureDetailsResponseDTO.java
  Backend/src/main/java/fr/uge/structsure/entities/Sensor.java
  Backend/src/main/java/fr/uge/structsure/services/SensorService.java
Labels: MergeRequest

#213 #171 volet de capteur dynamique
  Backend/src/main/java/fr/uge/structsure/controllers/SensorController.java
  Backend/src/main/java/fr/uge/structsure/controllers/StructureController.java
  Backend/src/main/java/fr/uge/structsure/dto/sensors/EditSensorRequestDTO.java
  Backend/src/main/java/fr/uge/structsure/dto/sensors/EditSensorResponseDTO.java
  Backend/src/main/java/fr/uge/structsure/dto/sensors/SensorDTO.java
  Backend/src/main/java/fr/uge/structsure/entities/Sensor.java
  Backend/src/main/java/fr/uge/structsure/exceptions/Error.java
  Backend/src/main/java/fr/uge/structsure/services/PlanService.java
  Backend/src/main/java/fr/uge/structsure/services/SensorService.java
  Frontend/src/assets/plan_not_found.png
  Frontend/src/components/AdminPanel/EditAccountModal.jsx
  Frontend/src/components/SensorFilter.jsx
  Frontend/src/components/SensorPanel/SensorFieldComponent.jsx
  Frontend/src/components/SensorPanel/SensorPanel.jsx
  Frontend/src/components/StructureDetail/StructureDetailBody.jsx
  Frontend/src/components/StructureDetail/StructureDetailCanvas.jsx
  Frontend/src/components/StructureDetail/StructureDetailCapteurs.jsx
  Frontend/src/components/StructureDetail/StructureDetailPlans.jsx
  Frontend/src/components/StructureDetail/StructureDetailRow.jsx
  Frontend/src/hooks/useFetch.js
  Frontend/src/hooks/vaildateUserAccountForm.js
Labels: MergeRequest

#215 #199 Prise en compte des capteurs sans position
  Backend/src/main/java/fr/uge/structsure/entities/Sensor.java
  Backend/src/main/java/fr/uge/structsure/repositories/SensorRepository.java
  Backend/src/main/java/fr/uge/structsure/services/SensorService.java
Labels: MergeRequest

#203 #137 Connexion en cours
  Android/app/libs/cslibrary4a-debug.aar
  Android/app/libs/cslibrary4a-release.aar
  Android/app/src/main/java/fr/uge/structsure/MainActivity.kt
  Android/app/src/main/java/fr/uge/structsure/bluetooth/presentation/BluetoothPage.kt
  Android/app/src/main/java/fr/uge/structsure/components/BluetoothButton.kt
  Android/app/src/main/java/fr/uge/structsure/connexionPage/Authentication.kt
  Android/app/src/main/java/fr/uge/structsure/connexionPage/Connexion.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/cache/SensorCache.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/dao/ScanDao.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/domain/ScanViewModel.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/ScanPage.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/ToolBar.kt
  Android/app/src/main/java/fr/uge/structsure/settingsPage/presentation/SettingsPage.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/presentation/HomePage.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/presentation/components/AccountInformationsView.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/presentation/components/StructureButtons.kt
Labels: MergeRequest

#221 #110 filtre et tri dynamique des capteurs
  Backend/src/main/java/fr/uge/structsure/controllers/SensorController.java
  Backend/src/main/java/fr/uge/structsure/dto/sensors/SensorByStructureResponseDTO.java
  Backend/src/main/java/fr/uge/structsure/exceptions/Error.java
  Backend/src/main/java/fr/uge/structsure/repositories/SensorRepositoryCriteriaQuery.java
  Backend/src/main/java/fr/uge/structsure/services/SensorService.java
  Frontend/src/components/Pagination.jsx
  Frontend/src/components/SensorFilter.jsx
  Frontend/src/components/SensorPanel/SensorFieldComponent.jsx
  Frontend/src/components/SensorPanel/SensorPanel.jsx
  Frontend/src/components/StructureDetail/StructureDetailBody.jsx
  Frontend/src/components/StructureDetail/StructureDetailCapteurs.jsx
  Frontend/src/components/StructureDetail/StructureDetailRow.jsx
Labels: MergeRequest

#202 #100 reglage de la sensibilite de linterrogateur
  Android/app/src/main/java/fr/uge/structsure/MainActivity.kt
  Android/app/src/main/java/fr/uge/structsure/components/Containers.kt
  Android/app/src/main/java/fr/uge/structsure/components/Fields.kt
  Android/app/src/main/java/fr/uge/structsure/database/AppDatabase.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/domain/ScanViewModel.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/ScanPage.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/components/ScanWeather.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/components/SensorsList.kt
  Android/app/src/main/java/fr/uge/structsure/settingsPage/presentation/PreferencesManager.kt
  Android/app/src/main/java/fr/uge/structsure/settingsPage/presentation/SettingsPage.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/Sensor.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/domain/ConnectivityViewModel.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/domain/StructureViewModel.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/presentation/HomePage.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/presentation/components/SearchBar.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/presentation/components/StructuresListView.kt
Labels: MergeRequest

#216 #161 note de capteur
  Android/app/src/main/java/fr/uge/structsure/components/Fields.kt
  Android/app/src/main/java/fr/uge/structsure/database/AppDatabase.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/ResultSensors.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/ScanEdits.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/ScanEditsDao.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/dao/ScanDao.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/network/dto/ScanEditDTO.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/network/dto/ScanRequestDTO.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/network/dto/ScanResultDTO.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/repository/ScanRepository.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/domain/ScanViewModel.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/ScanPage.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/SensorDao.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/StructureDao.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/StructureRepository.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/domain/StructureViewModel.kt
  Backend/src/main/java/fr/uge/structsure/dto/scan/AndroidScanResultDTO.java
  Backend/src/main/java/fr/uge/structsure/dto/scan/AndroidSensorEditDTO.java
  Backend/src/main/java/fr/uge/structsure/dto/scan/AndroidSensorResultDTO.java
  Backend/src/main/java/fr/uge/structsure/entities/Result.java
  Backend/src/main/java/fr/uge/structsure/entities/SensorId.java
  Backend/src/main/java/fr/uge/structsure/exceptions/Error.java
  Backend/src/main/java/fr/uge/structsure/repositories/SensorRepository.java
  Backend/src/main/java/fr/uge/structsure/repositories/SensorRepositoryCriteriaQuery.java
  Backend/src/main/java/fr/uge/structsure/services/ScanService.java
Labels: MergeRequest

#218 #209 filtre et tri des capteurs
  Android/app/src/main/java/fr/uge/structsure/MainActivity.kt
  Android/app/src/main/java/fr/uge/structsure/components/Fields.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/components/SensorsList.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/FilterOption.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/SortOption.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/presentation/components/SearchBar.kt
  Android/app/src/main/res/drawable/arrow_down_narrow_wide.xml
  Android/app/src/main/res/drawable/checkmark.xml
  Android/app/src/main/res/drawable/chevron_up.xml
  Android/app/src/main/res/drawable/sort_asc.xml
  Android/app/src/main/res/drawable/sort_desc.xml
Labels: MergeRequest

#214 #160 modale capteur dynamique
  Android/app/src/main/java/fr/uge/structsure/MainActivity.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/PlanTree.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/cache/SensorCache.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/domain/PlanViewModel.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/domain/ScanViewModel.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/ScanPage.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/components/SensorState.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/StructureRepository.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/domain/StructureViewModel.kt
Labels: MergeRequest

#220 #206 interface ajout note scan
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/dao/ResultDao.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/dao/ScanDao.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/repository/ScanRepository.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/domain/ScanViewModel.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/ScanPage.kt
  Backend/src/main/java/fr/uge/structsure/dto/scan/AndroidScanResultDTO.java
Labels: MergeRequest

#230 #173 modification des droits par ouvage
  Backend/src/main/java/fr/uge/structsure/controllers/UserAccountController.java
  Backend/src/main/java/fr/uge/structsure/dto/userAccount/accountStructure/GetStructureListForUserAccountsResponseDTO.java
  Backend/src/main/java/fr/uge/structsure/dto/userAccount/accountStructure/StructureAcessDetails.java
  Backend/src/main/java/fr/uge/structsure/services/AccountService.java
  Frontend/src/components/AdminPanel/AccountStructureSection.jsx
  Frontend/src/components/AdminPanel/AddAccountModal.jsx
  Frontend/src/components/AdminPanel/EditAccountModal.jsx
  Frontend/src/components/Pagination.jsx
  Frontend/src/components/SensorPanel/Canvas.jsx
  Frontend/src/components/SensorPanel/SensorPanel.jsx
  Frontend/src/components/StructureDetail/StructureDetailBody.jsx
  Frontend/src/components/StructureDetail/StructureDetailCapteurs.jsx
  Frontend/src/components/StructureDetail/StructureDetailHead.jsx
  Frontend/src/components/StructureNameCard.jsx
Labels: MergeRequest

#222 #204 poser un capteur sur un plan
  Android/app/src/main/java/fr/uge/structsure/MainActivity.kt
  Android/app/src/main/java/fr/uge/structsure/components/Containers.kt
  Android/app/src/main/java/fr/uge/structsure/components/Plan.kt
  Android/app/src/main/java/fr/uge/structsure/database/AppDatabase.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/ScanEdits.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/ScanEntity.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/cache/SensorCache.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/dao/ScanDao.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/network/dto/ScanEditDTO.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/repository/ScanRepository.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/domain/PlanViewModel.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/domain/ScanViewModel.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/PlansView.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/components/ScanWeather.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/components/SensorsList.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/Sensor.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/SensorDao.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/StructureDao.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/domain/StructureViewModel.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/presentation/components/SearchBar.kt
  Android/app/src/main/res/drawable/trash.xml
  Backend/src/main/java/fr/uge/structsure/dto/scan/AndroidSensorEditDTO.java
  Backend/src/main/java/fr/uge/structsure/services/ScanService.java
Labels: MergeRequest

#234 #172 restrictions acces
  Backend/src/main/java/fr/uge/structsure/controllers/StructureController.java
  Backend/src/main/java/fr/uge/structsure/dto/userAccount/accountStructure/GetStructureListForUserAccountsResponseDTO.java
  Backend/src/main/java/fr/uge/structsure/dto/userAccount/accountStructure/StructureAccessDetails.java
  Backend/src/main/java/fr/uge/structsure/services/AccountService.java
  Backend/src/main/java/fr/uge/structsure/services/AuthValidationService.java
  Backend/src/main/java/fr/uge/structsure/services/StructureService.java
  Frontend/src/App.jsx
  Frontend/src/components/AdminPanel/AccountStructureSection.jsx
  Frontend/src/components/AdminPanel/EditAccountModal.jsx
  Frontend/src/components/AdminPanelBody.jsx
  Frontend/src/components/SensorFilter.jsx
  Frontend/src/components/StructSureBody.jsx
  Frontend/src/components/StructureDetail/StructureDetailBody.jsx
  Frontend/src/components/StructureDetail/StructureDetailCapteurs.jsx
Labels: MergeRequest

#225 #224 redirection et login
  Backend/src/main/java/fr/uge/structsure/controllers/FrontController.java
  Frontend/src/App.jsx
  Frontend/src/components/AdminPanel/AddAccountModal.jsx
  Frontend/src/components/AdminPanel/EditAccountModal.jsx
  Frontend/src/components/AdminPanelBody.jsx
  Frontend/src/components/Login.jsx
  Frontend/src/components/LstStructureHead.jsx
  Frontend/src/components/Plan/ModalAddPlan.jsx
  Frontend/src/components/Plan/ModalEditPlan.jsx
  Frontend/src/components/Sensor/ModalAddSensor.jsx
  Frontend/src/components/SensorFilter.jsx
  Frontend/src/components/SensorPanel/SensorPanel.jsx
  Frontend/src/components/StructSureBody.jsx
  Frontend/src/components/StructureDetail/StructureDetailBody.jsx
  Frontend/src/components/StructureDetail/StructureDetailCanvas.jsx
  Frontend/src/components/StructureDetail/StructureDetailEdit.jsx
  Frontend/src/hooks/useFetch.js
Labels: MergeRequest

#236 #211 anonymiser un compte
  Backend/src/main/java/fr/uge/structsure/controllers/UserAccountController.java
  Backend/src/main/java/fr/uge/structsure/entities/Account.java
  Backend/src/main/java/fr/uge/structsure/services/AccountService.java
  Backend/src/main/java/fr/uge/structsure/services/AccountStructureService.java
  Frontend/src/components/AdminPanel/EditAccountModal.jsx
Labels: MergeRequest

#235 #210 supprimer-un-point-dun-plan
  Backend/src/main/java/fr/uge/structsure/controllers/SensorController.java
  Backend/src/main/java/fr/uge/structsure/dto/sensors/DeletePositionSensorResponseDTO.java
  Backend/src/main/java/fr/uge/structsure/services/SensorService.java
  Frontend/src/components/StructureDetail/StructureDetailBody.jsx
  Frontend/src/components/StructureDetail/StructureDetailCanvas.jsx
  Frontend/src/components/StructureDetail/StructureDetailPlans.jsx
Labels: MergeRequest

#231 #208 modale ajout capteur
  Android/app/src/main/java/fr/uge/structsure/components/Containers.kt
  Android/app/src/main/java/fr/uge/structsure/components/CustomToast.kt
  Android/app/src/main/java/fr/uge/structsure/components/Fields.kt
  Android/app/src/main/java/fr/uge/structsure/components/Page.kt
  Android/app/src/main/java/fr/uge/structsure/components/Plan.kt
  Android/app/src/main/java/fr/uge/structsure/connexionPage/Connexion.kt
  Android/app/src/main/java/fr/uge/structsure/retrofit/SensorApi.kt
  Android/app/src/main/java/fr/uge/structsure/retrofit/ServerStatusApi.kt
  Android/app/src/main/java/fr/uge/structsure/retrofit/response/GetALLSensors.kt
  Android/app/src/main/java/fr/uge/structsure/retrofit/response/ServerStatusResponse.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/ScanEdits.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/SensorValidator.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/network/dto/ScanEditDTO.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/network/dto/SensorEditDTO.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/repository/ScanRepository.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/domain/PlanViewModel.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/domain/ScanViewModel.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/PlansView.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/ScanPage.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/components/SensorsList.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/Sensor.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/SensorDao.kt
  Backend/src/main/java/fr/uge/structsure/controllers/AndroidScanController.java
  Backend/src/main/java/fr/uge/structsure/controllers/AuthenticationController.java
  Backend/src/main/java/fr/uge/structsure/controllers/SensorController.java
  Backend/src/main/java/fr/uge/structsure/controllers/StructureController.java
  Backend/src/main/java/fr/uge/structsure/controllers/UserAccountController.java
  Backend/src/main/java/fr/uge/structsure/dto/scan/AndroidSensorEditDTO.java
  Backend/src/main/java/fr/uge/structsure/dto/sensors/SensorPositionRequestDTO.java
  Backend/src/main/java/fr/uge/structsure/entities/Sensor.java
  Backend/src/main/java/fr/uge/structsure/exceptions/TraitementException.java
  Backend/src/main/java/fr/uge/structsure/services/ScanService.java
  Backend/src/main/java/fr/uge/structsure/services/SensorService.java
Labels: MergeRequest

#232 #209 note ouvrage
  Android/app/src/main/java/fr/uge/structsure/database/AppDatabase.kt
  Android/app/src/main/java/fr/uge/structsure/retrofit/response/GetAllStructureResponse.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/network/dto/ScanRequestDTO.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/network/dto/SensorEditDTO.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/data/repository/ScanRepository.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/domain/ScanViewModel.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/ScanPage.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/components/ScanWeather.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/StructureDao.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/StructureData.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/StructureRepository.kt
  Backend/src/main/java/fr/uge/structsure/dto/scan/AndroidScanResultDTO.java
  Backend/src/main/java/fr/uge/structsure/dto/structure/AllStructureResponseDTO.java
  Backend/src/main/java/fr/uge/structsure/repositories/StructureRepositoryCriteriaQuery.java
  Backend/src/main/java/fr/uge/structsure/services/ScanService.java
Labels: MergeRequest

#233 #205 afficher le point dans la modale de capteur
  Android/app/src/main/java/fr/uge/structsure/MainActivity.kt
  Android/app/src/main/java/fr/uge/structsure/alertes/Plan.kt
  Android/app/src/main/java/fr/uge/structsure/components/Buttons.kt
  Android/app/src/main/java/fr/uge/structsure/components/Plan.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/domain/AlertInfo.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/domain/PlanViewModel.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/domain/ScanViewModel.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/AlertPage.kt
  Android/app/src/main/java/fr/uge/structsure/scanPage/presentation/ScanPage.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/data/SensorDao.kt
  Android/app/src/main/java/fr/uge/structsure/structuresPage/presentation/components/UserInformations.kt
  Android/app/src/main/res/drawable/red_bluetooth.xml
  Android/app/src/main/res/layout/activity_scan.xml
  Backend/src/main/java/fr/uge/structsure/services/ScanService.java
  Backend/src/test/java/fr/uge/structsure/StructsureBackendApplicationTests.java
Labels: MergeRequest
